### PR TITLE
fix(SHRINKRES-298): Fix embedded tests on Windows

### PR DESCRIPTION
**Pull request by famod**
The main change is the addition of `TestWorkDirRule`. I hope its JavaDoc explains its purpose sufficiently.

*Please note that this is also based on #139 to strive for green builds!* I will gladly rebase this on `master`, once #139 is merged.

### CODE REVIEW

**Comment by famod** [comment]
Rebased on `master` which now already contains #139.

**Comment by famod** [comment]
> I think the next reasonable step would be to actually add Windows-based machine to our tests.
Sounds logical!

> I'm thinking - maybe we should move from Travis to Circle.
I am not familiar with CircleCI but TravisCI but it indeed seems that Travis does not support Java on WIndows yet: https://docs.travis-ci.com/user/reference/windows/

**Comment by bartoszmajsak** [comment]
My general observation about Travis is that it's getting less and less reliable. I'm happily using Circle in other projects so the move should be rather easy.

**Comment by famod** [comment]
@bartoszmajsak Thanks for merging! It is great to see again some activity in this project.

Btw: Today I'm going to create another PR, this time for https://issues.redhat.com/browse/SHRINKRES-299

**Comment by bartoszmajsak** [comment]
@famod awesome - do you want me to wait for this fix before cutting the release? Was actually planning to do that today.

**Comment by famod** [comment]
@bartoszmajsak 
> do you want me to wait for this fix before cutting the release?

Oh yes, please! There might be a delay because my approach might raise some concerns but I think we'll cope with that just fine.

**Comment by bartoszmajsak** [comment]
@famod Sure, bring it in! :)

**Pull request merged**
