### PR TITLE
[SHRINKRES-132] rename from MavenImporter to MavenBuilder

### PR DESCRIPTION
**Pull request by mmatloka**
https://issues.jboss.org/browse/SHRINKRES-132

### CODE REVIEW

**Comment by MatousJobanek** [comment]
Hi,
I started working on SWR 3.0.0-alpha-1 and I'd like to include this refactoring issue into the release. Having considered all your suggestions I have three proposals. Could you please take a look at it and write what do you think or add some improvement proposals? Thanks
https://developer.jboss.org/message/956959

**Comment by ALRubinger** [comment]
@MatousJobanek Is this still relevant?

**Comment by MatousJobanek** [comment]
What do you mean @ALRubinger ? My comment or this PR? 
PR - can be closed
my comment - this is what I'm currently working on.

**Comment by ALRubinger** [comment]
The issue as raised by the PR. :)  I'll leave to you to close things as appropriate then!

**Comment by MatousJobanek** [comment]
Closing this PR as it is outdated and doesn't correspond to the final API we agreed on https://developer.jboss.org/message/956959

**Pull request closed without merging**
