### PR TITLE
Fix for directory entry for root folder

### PR DESCRIPTION
**Pull request by oliveti**
Root folder should not be included in the output zip because "file" is equals to "root".  

An exception is raised without this fix by this line : _file.getAbsolutePath().substring(root.getAbsolutePath().length() + 1).replace(File.separatorChar, '/');_

### CODE REVIEW

**Comment by kpiwko** [comment]
@oliveti is there a chance that you could provide test case in test package?

**Comment by oliveti** [comment]
@kpiwko, I just pushed a unit test to create and check a zip archive.

**Comment by MatousJobanek** [comment]
Hi, sorry for a long inactivity. I took a look at your PR - do you know about any test case, where the api is used instead of accessing the class MavenResolvedArtifactImpl.PackageDirHelper directly?

**Comment by MatousJobanek** [comment]
I've changed the test case
Your PR has been merged, thanks

**Pull request closed without merging**
