### PR TITLE
SHRINKRES-242 Added missing licence headers

### PR DESCRIPTION
**Pull request by MatousJobanek**

### CODE REVIEW

**Comment by ALRubinger** [comment]
Per advice of legal counsel, license headers should not be used (LICENSE file in the root of the repo is required, however)

**Comment by MatousJobanek** [comment]
Do you have any reference/article? I have very limited knowledge in this area, so any advice would be helpful :-).

**Comment by ALRubinger** [comment]
@MatousJobanek Sadly no; I believe that bit came from an internal thread from @richardfontana; recommend emailing him for proper clarification.

**Comment by gunnarmorling** [comment]
FWIW, for Hibernate, Debezium and others we're using short concise file headers like this:

```java
/*
 * Hibernate Validator, declare and validate application constraints
 *
 * License: Apache License, Version 2.0
 * See the license.txt file in the root directory or <http://www.apache.org/licenses/LICENSE-2.0>.
 */
```

I.e. no year or company name that may need adjusting over time :)

**Pull request closed without merging**
