### PR TITLE
feat(SHRINKWRAP-524) - Support Maven 3.6

### PR DESCRIPTION
**Pull request by apupier**
- update version from 3.5.2 to 3.6.1
- change org.eclipse.aether.internal.impl.DefaultDependencyCollector to
org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector
- add com.google.guava:guava as dependencies as it is no more provided
by Maven. Using latest version requires to update also Predicate usage.

This PR is to start discussion.
With current state, I'm not sure that we will be able to use it with previous Maven version inside Maven plugins (such as [Syndesis maven plugin](https://github.com/syndesisio/syndesis/tree/master/app/extension/maven-plugin)). if it is the case, we will need to move version to 4.0.0 I guess.
I have several tests failing locally but they were failing with previous version too.

### CODE REVIEW

**Comment by bartoszmajsak** [comment]
Many thanks for your contribution @apupier.

I would like to hear opinion from @MatousJobanek about proposed changes.

I just have one observation I wanted to bring up:

> add com.google.guava:guava as dependencies as it is no more provided
by Maven. Using latest version requires to update also Predicate usage.

I think using 2.6MB library for just one predicate (I just checked :)) is a bit of overdoing. Since you already touched that code do you think you could rework it to make us Guava-free?

**Comment by bartoszmajsak** [comment]
@MatousJobanek I see we are also having issues with Travis, something we have to address before merging this PR (or any other)

**Comment by apupier** [comment]
> I think using 2.6MB library for just one predicate (I just checked :)) is a bit of overdoing. Since you already touched that code do you think you could rework it to make us Guava-free?

agree, just wanted to change minimal things first.
provided an additional commit using a for-loop and removing guava

**Comment by apupier** [comment]
> With current state, I'm not sure that we will be able to use it with previous Maven version inside Maven plugins (such as [Syndesis maven plugin](https://github.com/syndesisio/syndesis/tree/master/app/extension/maven-plugin)).

the current failures on CI seems to show that it is not working:

```
[[1;34mINFO[m] [debug] Propagating [maven.execution.global-settings=/home/travis/.m2/wrapper/dists/apache-maven-3.5.2-bin/28qa8v9e2mq69covern8vmdkj0/apache-maven-3.5.2/conf/settings.xml] from Maven Session to command line properties
[[1;34mINFO[m] [debug] Propagating [maven.execution.active-profiles=standard-with-extra-repos] from Maven Session to command line properties
[[1;34mINFO[m] [INFO] ------------------------------------------------------------------------
[[1;34mINFO[m] [INFO] BUILD FAILURE
[[1;34mINFO[m] [INFO] ------------------------------------------------------------------------
[[1;34mINFO[m] [INFO] Total time: 2.200 s
[[1;34mINFO[m] [INFO] Finished at: 2019-07-05T10:06:27Z
[[1;34mINFO[m] [INFO] Final Memory: 14M/189M
[[1;34mINFO[m] [INFO] ------------------------------------------------------------------------
[[1;34mINFO[m] [ERROR] Failed to execute goal org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-maven-plugin:3.1.4-SNAPSHOT:dependency-tree (default-cli) on project shrinkwrap-resolver-maven-plugin-tests-dependency-tree: Execution default-cli of goal org.jboss.shrinkwrap.resolver:shrinkwrap-resolver-maven-plugin:3.1.4-SNAPSHOT:dependency-tree failed: Unable to invoke onlyOne([Ljava.lang.Class;@5e4fa1da) on object org.jboss.shrinkwrap.resolver.spi.loader.ServiceRegistry with parameters [Ljava.lang.Object;@588cd519: InvocationTargetException: Could not create new service instance: org/eclipse/aether/internal/impl/collect/DefaultDependencyCollector: org.eclipse.aether.internal.impl.collect.DefaultDependencyCollector -> [Help 1]
```

**Comment by apupier** [comment]
discovered that there is another place with a maven version defined: https://github.com/shrinkwrap/resolver/blob/e881a84b8cff5b0a014f2a5ebf612be3eb9db01f/bom/pom.xml#L49 Does it need to be changed too?

**Comment by MatousJobanek** [comment]
Ha, looks like some zombie error. Yes, update it there as well please - and you can also use the variable in the dependency. Thanks a lot

**Comment by andresluuk** [comment]
Saad to see that this has not gotten in jet.
It has been annoying to see:
java.lang.NoSuchMethodError: 'org.codehaus.plexus.util.cli.CommandLineException org.apache.maven.shared.invoker.InvocationResult.getExecutionException()'
all the time when the maven build called with shrinkwrap fails.

**Comment by famod** [comment]
@apupier @MatousJobanek Any chance to get this updated to Maven 3.6.3 and have it merged? Thanks!

**Comment by bartoszmajsak** [comment]
Closing in favor of #140

**Pull request closed without merging**
