### PR TITLE
feat(SHRINKWRAP-524): Upgrade to Maven 3.6.3

### PR DESCRIPTION
**Pull request by famod**
Based on #137 by @apupier + yet another upgrade from 3.6.1 to latest 3.6.3.

*Please note that this is also based on #139 to strive for green builds!* I will gladly rebase this on `master`, once #139 is merged.

### CODE REVIEW

**Comment by famod** [comment]
Rebased on `master` which now already contains #139.

**Comment by bartoszmajsak** [comment]
Thanks!

**Comment by bartoszmajsak** [comment]
@famod no need to rebase, you can simply just update the branch from here next time. Thanks for your contribution.

**Comment by famod** [comment]
@bartoszmajsak 
> no need to rebase, you can simply just update the branch from here next time. 

Sorry if I'm being stupid, but what do you mean with "update the branch from here"?
Is there a GitHub feature for that?

The thing is: I don't like to "pollute" my PRs with merge commits (which then might end up in `master`). That's why I like to rebase instead.

**Comment by bartoszmajsak** [comment]
There' should be a button saying "update the branch" - 
image

It would be weird to not have it available for the author of the PR, but maybe that is the case.

As for merge commits - that doesn't really matter if you ask me, as at the end PR is squashed and lands as one commit in `master` :) But I totally applaud your desire to have a clean history. Not sure if that's still the case, but I recall rebase/force push was messing up the existing PR review if comments were done on the wiped commits.

**Pull request merged**
